IDAM-611 Convert AD Account Creation Rule to Action
nice-digital/identity-hostedpages pull request #167
Opened 2024-06-06 15:24 UTC by AlexPowell-nice

https://nicedigital.atlassian.net/browse/IDAM-611

2024-06-12 11:15 UTC, tresaknice requested changes

2024-06-12 11:15 UTC, tresaknice commented on custom-pages/actions/Initial AD login Creates Account in Identity/code.js
> +      var addUserResponse
Semicolon is missing

2024-06-12 11:15 UTC, tresaknice commented on custom-pages/actions/Initial AD login Creates Account in Identity/code.js
> +        tokenResponse = await tokenPromise;
Is there a need for await? Already const tokenPromise(line 39) is awaiting the fetch. The next steps will be executed only once the await fetch() is completed.

2024-06-12 11:15 UTC, tresaknice commented on custom-pages/actions/Initial AD login Creates Account in Identity/code.js
> +        addUserResponse = await addUserPromise;
Is there a need for await?

2024-06-12 13:33 UTC, tresaknice approved these changes

2024-07-04 07:47 UTC, mgallagher1980 approved these changes

2024-07-04 09:57 UTC, merged