IDAM-612 Convert Post Change Password Hook To Action
nice-digital/identity-hostedpages pull request #170
Opened 2024-06-20 15:29 UTC by AlexPowell-nice

https://nicedigital.atlassian.net/browse/IDAM-612

2024-06-20 15:52 UTC, tresaknice requested changes

2024-06-20 15:52 UTC, tresaknice commented on custom-pages/actions/Post Change Password - Create IDAM User/code.js
> +  var userExistsResponse;
Can "var" be changed to "let" to keep it consistent with the rest of the code.

2024-06-20 15:52 UTC, tresaknice commented on custom-pages/actions/Post Change Password - Create IDAM User/code.js
> +  var checkNICEAccountsResponse;
Can "var" be changed to "let"

2024-06-20 15:52 UTC, tresaknice commented on custom-pages/actions/Post Change Password - Create IDAM User/code.js
> +  let user = JSON.parse(await checkNICEAccountsResponse.text())
can this be changed to const as the user is not being reassigned

2024-06-20 15:52 UTC, tresaknice commented on custom-pages/actions/Post Change Password - Create IDAM User/code.js
> +    'nameIdentifier': `auth0|${user.user_id}`,
would there be a situation where "user" could be null?

2024-06-20 15:52 UTC, tresaknice commented on custom-pages/actions/Post Change Password - Create IDAM User/code.js
> +  var addUserResponse;
Can "var" be changed to "let"

2024-06-20 16:08 UTC, tresaknice approved these changes

2024-07-02 08:21 UTC, mgallagher1980 submitted a review, later dismissed

2024-07-04 16:11 UTC, mgallagher1980 approved these changes

2024-07-04 16:11 UTC, merged